# Codecov
CODECOV_TOKEN=

# Elasticsearch
ELASTICSEARCH_HOST=https://elastic-cloud.com:9200
ELASTICSEARCH_USER=elastic
ELASTICSEARCH_PASSWORD=
ELASTICSEARCH_CLOUD_ID=
ELASTICSEARCH_API_KEY=
ELASTICSEARCH_API_KEY_ID=
ELASTICSEARCH_API_KEY_SECRET=
ELASTICSEARCH_PROXY=
ELASTICSEARCH_REQUEST_TIMEOUT=

# Google
GOOGLE_OAUTH_WEB=False
GOOGLE_OAUTH_DESKTOP=True
GOOGLE_AUTH_URI=
GOOGLE_CERT_URL=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_TOKEN=
GOOGLE_TOKEN_URI=
GOOGLE_PROJECT_ID=
GOOGLE_REFRESH_TOKEN=

# Instagram
INSTAGRAM_LOGIN=
INSTAGRAM_PASSWORD=

# Minio
MINIO_ENDPOINT=play.minio.io:9000
MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
MINIO_SESSION_TOKEN=
MINIO_SECURE=
MINIO_REGION=
MINIO_HTTP_CLIENT=

# Neo4j
NEO4J_USER=neo4j
NEO4J_PASSWORD=neo4j
NEO4J_HOST=bolt://neo4j:7687

# Openstack Swift Auth
OPENSTACK_USERNAME=
OPENSTACK_PASSWORD=""
OPENSTACK_AUTH_URL=
OPENSTACK_PROJECT_ID=
OPENSTACK_PROJECT_NAME=""
OPENSTACK_USER_DOMAIN_NAME=""
OPENSTACK_PROJECT_DOMAIN_ID=""
OPENSTACK_REGION_NAME=""
OPENSTACK_INTERFACE=public
OPENSTACK_IDENTITY_API_VERSION=3
SWIFTCLIENT_INSECURE=True

# Splunk SOAR
SPLUNK_SOAR_HOST=
SPLUNK_SOAR_AUTH_TOKEN=
SPLUNK_SOAR_USER=
SPLUNK_SOAR_PASSWORD=

# Pypi
PKG=automon
PYPI=automonisaur
TWINE_REPOSITORY=https://upload.pypi.org/legacy/
TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
TWINE_USERNAME=__token__
TWINE_PASSWORD=

# Selenium
SELENIUM_CHROMEDRIVER_PATH=
SELENIUM_OPT=

# Sentry.io
SENTRY_DSN=
SENTRY_ENVIRONMENT=
SENTRY_RELEASE=

# Slack Auth
SLACK_WEBHOOK=""
SLACK_PROXY=""
SLACK_TOKEN=""
SLACK_USER=
SLACK_DEFAULT_CHANNEL=
SLACK_INFO_CHANNEL=
SLACK_DEBUG_CHANNEL=
SLACK_ERROR_CHANNEL=
SLACK_CRITICAL_CHANNEL=
SLACK_WARN_CHANNEL=
SLACK_TEST_CHANNEL=

# Shodan
SHODAN_API=

# Splunk
SPLUNK_HOST=splunkcloud.com
SPLUNK_PORT=8089
SPLUNK_USERNAME=
SPLUNK_PASSWORD=


# Swift buckets
SWIFT_SOURCE_BUCKET=
SWFT_BACKUP_BUCKET=

# VDS
VDS_SERVER=
VDS_PORT=
LDAP_PORT=
VDS_BIND_USER=cn=automon,ou=people,dc=automon,dc=com
VDS_BASE_DN=dc=automon,dc=com
VDS_PASSWORD=
