# Codecov
CODECOV_TOKEN=

# Datadog
DD_SITE=https://us5.datadoghq.com
DD_API_KEY=
DD_APP_KEY=

# Elasticsearch
ELASTICSEARCH_HOST=https://elastic-cloud.com:9200
ELASTICSEARCH_USER=elastic
ELASTICSEARCH_PASSWORD=
ELASTICSEARCH_CLOUD_ID=
ELASTICSEARCH_API_KEY=
ELASTICSEARCH_API_KEY_ID=
ELASTICSEARCH_API_KEY_SECRET=
ELASTICSEARCH_PROXY=
ELASTICSEARCH_REQUEST_TIMEOUT=

# Flask
FLASK_HOST=127.0.0.1
FLASK_PORT=5000
FLASK_DEBUG=true

# Google
GOOGLE_OAUTH_WEB=False
GOOGLE_OAUTH_DESKTOP=True
GOOGLE_AUTH_URI=
GOOGLE_CERT_URL=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_TOKEN=
GOOGLE_TOKEN_URI=
GOOGLE_PROJECT_ID=
GOOGLE_REFRESH_TOKEN=

# Instagram
INSTAGRAM_LOGIN=
INSTAGRAM_PASSWORD=

# Minio
MINIO_ENDPOINT=play.minio.io:9000
MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
MINIO_SESSION_TOKEN=
MINIO_SECURE=
MINIO_REGION=
MINIO_HTTP_CLIENT=

# Neo4j
NEO4J_USER=neo4j
NEO4J_PASSWORD=neo4j
NEO4J_HOST=bolt://neo4j:7687

# Openstack Swift Auth
OPENSTACK_USERNAME=
OPENSTACK_PASSWORD=""
OPENSTACK_AUTH_URL=
OPENSTACK_PROJECT_ID=
OPENSTACK_PROJECT_NAME=""
OPENSTACK_USER_DOMAIN_NAME=""
OPENSTACK_PROJECT_DOMAIN_ID=""
OPENSTACK_REGION_NAME=""
OPENSTACK_INTERFACE=public
OPENSTACK_IDENTITY_API_VERSION=3
SWIFTCLIENT_INSECURE=True

# OpenTelemetry
# https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/logging/logging.html
OTEL_PYTHON_LOG_CORRELATION=true
OTEL_PYTHON_LOG_FORMAT='%(asctime)s\t%(levelname)s\t[%(name)s]\t[%(filename)s:%(lineno)d]\t[trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s trace_sampled=%(otelTraceSampled)s]\t%(message)s'
OTEL_PYTHON_LOG_LEVEL=debug
# https://opentelemetry.io/docs/languages/python/automatic/
OTEL_SERVICE_NAME=your-service-name
OTEL_TRACES_EXPORTER=console,otlp
OTEL_METRICS_EXPORTER=console
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=0.0.0.0:4317

# Splunk SOAR
SPLUNK_SOAR_HOST=
SPLUNK_SOAR_AUTH_TOKEN=
SPLUNK_SOAR_USER=
SPLUNK_SOAR_PASSWORD=

# Swimlane
SWIMLANE_HOST=
SWIMLANE_USERNAME=
SWIMLANE_PASSWORD=
SWIMLANE_APIKEY=
SWIMLANE_JWT_TOKEN=
SWIMLANE_APP_ID=

# Pypi
PKG=automon
PYPI=automonisaur
TWINE_REPOSITORY=https://upload.pypi.org/legacy/
TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
TWINE_USERNAME=__token__
TWINE_PASSWORD=

# Selenium
SELENIUM_CHROMEDRIVER_PATH=
SELENIUM_OPT=
SELENIUM_COOKIES_BASE64=
SELENIUM_COOKIES_FILE=

# Sentry.io
SENTRY_DSN=
SENTRY_ENVIRONMENT=
SENTRY_RELEASE=

# Slack Auth
SLACK_WEBHOOK=""
SLACK_PROXY=""
SLACK_TOKEN=""
SLACK_USER=
SLACK_DEFAULT_CHANNEL=
SLACK_INFO_CHANNEL=
SLACK_DEBUG_CHANNEL=
SLACK_ERROR_CHANNEL=
SLACK_CRITICAL_CHANNEL=
SLACK_WARN_CHANNEL=
SLACK_TEST_CHANNEL=

# Shodan
SHODAN_API=

# Splunk
SPLUNK_HOST=splunkcloud.com
SPLUNK_PORT=8089
SPLUNK_USERNAME=
SPLUNK_PASSWORD=


# Swift buckets
SWIFT_SOURCE_BUCKET=
SWFT_BACKUP_BUCKET=

# VDS
VDS_SERVER=
VDS_PORT=
LDAP_PORT=
VDS_BIND_USER=cn=automon,ou=people,dc=automon,dc=com
VDS_BASE_DN=dc=automon,dc=com
VDS_PASSWORD=

# Wdutil
WDUTIL_PASSWORD=
