import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="automonisaur",
    version="0.6.25",
    author="naisanza",
    author_email="naisanza@gmail.com",
    description="Core libraries for automonisaur",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/TheShellLand/automonisaur",
    packages=setuptools.find_packages(),
    tests_require=["pytest"],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    ],
    license_files="LICENSE",
    python_requires='>=3.10',
    install_requires=[
        'Flask-Login>=0.5.0',
        'Flask-WTF>=0.15.1',
        'Flask>=2.0.1',
        'Scrapy>=2.6.0',
        'bcrypt>3.1.7',
        'beautifulsoup4>=4.10.0',
        'coverage>=5.4',
        'ddtrace>=2.7.6',
        'deprecation>=2.1.0',
        'elasticsearch>=7.14.0',
        'flask',
        'google-api-python-client>=2.39.0',
        'google-auth',
        'google-auth-httplib2>=0.1.0',
        'google-auth-oauthlib>=0.5.0',
        'jupyterlab>=3.1.9',
        'lxml>=4.7.1',
        'lxml>=4.7.1',
        'mcp',
        'minio>=7.1.0',
        'neo4j>=4.4.9',
        'nest-asyncio>=1.5.1',
        'numpy>=1.19.5',
        'ollama',
        'opentelemetry-distro==0.43b0',
        'opentelemetry-exporter-otlp==1.22.0',
        'opentelemetry-instrumentation-logging==0.43b0',
        'pandas>=1.1.5',
        'psutil>=5.8.0',
        'pytest-cov>=2.12.1',
        'pytest>=6.2.4',
        'python-keystoneclient>=4.2.0',
        'python-swiftclient>=3.12.0',
        'pytz>=2021.1',
        'requests',
        'requests>=2.26.0',
        'selenium>=3.141.0',
        'sentry-sdk>=1.5.1',
        'setuptools',
        'slackclient>=2.9.3',
        'splunk-sdk>=1.6.16',
        'swifter>=1.0.9',
        'twine',
        'typing_extensions',
        'urllib3>=1.26.6',
        'wheel',
        'xmltodict>=0.12.0'
    ]
)
