PROOFPOINT_CLOUD_HOST = 'https://threatprotection-api.proofpoint.com'
PROOFPOINT_CLOUD_SP = ''
PROOFPOINT_CLOUD_SECRET = ''
PROOFPOINT_CLOUD_EXPIRE = ''
PROOFPOINT_CLOUD_KEY_NAME = ''
PROOFPOINT_CERT_VERIFY = False
