name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: theshellland/automonisaur
  DOCKER_IMAGE: automonisaur

  PKG: automon
  PYPI: automonisaur
  TWINE_REPOSITORY: https://upload.pypi.org/legacy/
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_IMAGE }}
          outputs: type=docker,dest=/tmp/${{ env.DOCKER_IMAGE }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE }}.tar
          path: /tmp/${{ env.DOCKER_IMAGE }}.tar


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE }}.tar
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ env.DOCKER_IMAGE }}.tar
      - name: Run tests
        run: docker run -e PKG=${{ secrets.PKG }} -e PYPI=${{ secrets.PYPI }} -e TWINE_REPOSITORY=${{ secrets.TWINE_REPOSITORY }} -e TWINE_REPOSITORY_URL=${{ secrets.TWINE_REPOSITORY_URL }} -e TWINE_USERNAME=${{ secrets.TWINE_USERNAME }} -e TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }} ${{ env.DOCKER_IMAGE }} test


  publish-coverage:
    needs: test
    runs-on: ubuntu-latest
    # upload coverage report
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE }}
          path: /tmp
      - name: Load Docker image
        run: docker load --input /tmp/${{ env.DOCKER_IMAGE }}.tar
      - name: Upload coverage
        run: docker run ${{ env.DOCKER_IMAGE }} test html

#      - name: Codecov
#        uses: codecov/codecov-action@v1.0.12
#        with:
#          # User defined upload name. Visible in Codecov UI
#          name: # optional
#          # Repository upload token - get it from codecov.io. Required only for private repositories
#          token: # optional
#          # Path to coverage file to upload
#          file: # optional
#          # Comma-separated list of files to upload
#          files: # optional
#          # Directory to search for coverage reports.
#          directory: # optional
#          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
#          flags: # optional
#          # Write upload file to path before uploading
#          path_to_write_report: # optional
#          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
#          env_vars: # optional
#          # Specify whether or not CI build should fail if Codecov runs into an error during upload
#          fail_ci_if_error: # optional


  publish-pypi:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_IMAGE }}
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ env.DOCKER_IMAGE }}.tar

      - name: Upload to pypi
        run: docker run ${{ env.DOCKER_IMAGE }} upload


  publish-docker:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
